movieproject/account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path('login/', login, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout, name='logout'),
]

movieproject/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('detail/<int:id>', views.detail, name="detail"),
    path('comment/create/<int:id>', views.comment_create, name="comment_create"),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
import movie.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movie.views.index, name="index"),
    path('db/', movie.views.init_db, name="init_db"),
    path('movie/', include('movie.urls')),
    path('account/', include('account.urls')),    
]

movieproject/account/models.py
from django.db import models

# Create your models here.

movieproject/movie/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Movie(models.Model):
    title_kor = models.CharField(max_length=100)
    title_eng = models.CharField(max_length=100)
    poster_url = models.CharField(max_length=255, null=True)
    rating_aud = models.CharField(max_length=10)
    rating_cri = models.CharField(max_length=10)
    rating_net = models.CharField(max_length=10)
    rating_rut = models.FloatField(default=0) # 루튼 토마토 평점
    total_cnt = models.IntegerField(default=0) # 평가자 수
    genre = models.CharField(max_length=100)
    showtimes = models.CharField(max_length=10)
    release_date = models.CharField(max_length=20)
    rate = models.CharField(max_length=100)
    summary = models.TextField()


class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Staff(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=50)
    image_url = models.CharField(max_length=255, null=True)

movieproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def login(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']

    user = auth.authenticate(request, username=username, password=password)
    
    if user is not None:
      auth.login(request, user)
      return redirect('index')
    
    else:
      msg = "아이디 혹은 비밀번호가 일치하지 않습니다."
      return render(request, "login.html", {"msg" : msg})
    
  return render(request, 'login.html')

def signup(request):
  if request.method == 'POST':
    password1 = request.POST['password1']
    password2 = request.POST['password2']
    username = request.POST['username']
    
    if password1 == password2:
      try:
        user = User.objects.get(username=username)
        msg = "이미 사용중인 아이디입니다."
        return render(request, 'signup.html', {'msg' : msg})
      
      except User.DoesNotExist:
        user = User.objects.create_user(
          username = request.POST['username'],
          password = request.POST['password1'],
          )
        user.save()
        
        msg = "회원가입이 완료되었습니다. 다시 로그인해주세요."
        return render(request, 'login.html', {'msg' : msg})
    
    else:
      msg = "비밀번호가 일치하지 않습니다."
      return render(request, 'signup.html', {'msg' : msg})

  
  return render(request, 'signup.html')

def logout(request):
    auth.logout(request)
    return redirect('index')

movieproject/movie/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Staff, Comment
from .pagination_range import get_pagination_range
from django.core.paginator import Paginator

import requests

# Create your views here.
# test 123

def init_db(request):
    url = "http://3.36.240.145:3479/mutsa"
    res = requests.get(url)
    movies = res.json()['movies']
    for movie in movies:
        new_movie = Movie()
        new_movie.title_kor = movie['title_kor']
        new_movie.title_eng = movie['title_eng']
        new_movie.poster_url = movie['poster_url']
        new_movie.rating_aud = movie['rating_aud']
        new_movie.rating_cri = movie['rating_cri']
        new_movie.rating_net = movie['rating_net']
        new_movie.genre = movie['genre']
        new_movie.showtimes = movie['showtimes']
        new_movie.release_date = movie['release_date']
        new_movie.rate = movie['rate']
        new_movie.summary = movie['summary']
        new_movie.save()
        staffs = movie['staff']
        for staff in staffs:
            new_staff = Staff()
            new_staff.movie = new_movie
            new_staff.name = staff['name']
            new_staff.role = staff['role']
            new_staff.image_url = staff['image_url']
            new_staff.save()
    return redirect('index')


def index(request):
    if 'query' in request.GET:
        query = request.GET['query']
        movies = Movie.objects.filter(
            title_kor__contains=query
        ).order_by('title_kor')
    else:
        query = None
        movies = Movie.objects.all().order_by('title_kor')

    paginator = Paginator(movies, 8)
    page = request.GET.get('page', 1)
    paginated_movies = paginator.get_page(page)
    current_page = int(page) if page else 1
    max_index = len(paginator.page_range)
    start_index, end_index = get_pagination_range(current_page, max_index)
    page_num_range = paginator.page_range[start_index:end_index]

    if query:
        return render(request, 'index.html', {'movies': paginated_movies, 'page_range': page_num_range, 'query': query})
    else:
        return render(request, 'index.html', {'movies': paginated_movies, 'page_range': page_num_range})


def detail(request, id):
    movie = get_object_or_404(Movie, pk=id)
    staffs = Staff.objects.filter(movie=movie)
    comments = Comment.objects.filter(movie__pk=id)
    return render(request, 'detail.html', {'movie': movie, 'staffs': staffs, 'comments': comments})


def comment_create(request, id):
    movie_id = id
    comment = Comment()
    comment.movie = Movie.objects.get(pk=movie_id)
    comment.user = request.user
    if request.POST["content"]:
        comment.content = request.POST["content"]
        comment.save()
    return redirect('movie:detail', id)

movieproject/account/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>title</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <main class="form-signin">
      <br><br><br>
      <form action="{% url 'account:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-floating">
          <input type="text" class="form-control" name="username" id="floatingInput">
          <label for="floatingInput">아이디</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" name="password" id="floatingPassword">
          <label for="floatingPassword">비밀번호</label>
        </div>

        {% if msg %}
          {{msg}}
        {% endif %}

        <div class="checkbox mb-3">
          <label>
          </label>
        </div>
        <button style="margin-bottom: 10px;" type="submit" class="w-100 btn btn-lg btn-success">로그인</button>
      </form>
      <a href="{% url 'account:signup' %}"><button style="margin-bottom: 10px;" class="w-100 btn btn-lg btn-success">회원가입 하기</button></a>
      <a href="{% url 'index' %}"><button class="w-100 btn btn-lg btn-success">홈으로</button></a>
    </main>
  </body>
</html>

movieproject/account/templates/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>title</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
    <br><br><br>
    <form action="{% url 'account:signup' %}" method="POST">
      {% csrf_token %}
      <div class="form-floating">
        <input type="text" class="form-control" name="username" id="floatingInput">
        <label for="floatingInput">아이디</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" name="password1" id="floatingInput">
        <label for="floatingInput">비밀번호</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" name="password2" id="floatingInput">
        <label for="floatingInput">비밀번호 재입력</label>
      </div>

      {% if msg %}
        {{msg}}
      {% endif %}

      <div class="checkbox mb-3">
        <label>
        </label>
      </div>
      <button style="margin-bottom: 10px;" type="submit" class="w-100 btn btn-lg btn-success">회원가입</button>
  </form>
  <a href="{% url 'account:login' %}"><button style="margin-bottom: 10px;" class="w-100 btn btn-lg btn-success">로그인 하기</button></a>
  <a href="{% url 'index' %}"><button class="w-100 btn btn-lg btn-success">홈으로</button></a>
</main>
  </body>
</html>

movieproject/movie/templates/detail.html
{% extends 'base.html' %}
{% block css_content %}
<style>
    .comment-content {
        margin: 30px 0 50px 0;
    }

    .comment-content .form-control {
        width: 90%;
    }

    .comment-textarea {
        display: flex;
        justify-content: space-between;
    }

    .comment {
        width: 100%;
    }

    body {
        background-color: #fff;
    }

    .write-btn {
        margin: auto;
    }


    .addtxt {
        padding-top: 10px;
        padding-bottom: 10px;
        text-align: center;
        font-size: 13px;
        width: 350px;
        background-color: #e5e8ed;
        font-weight: 500
    }

    .form-control:focus {
        color: #000
    }

    .second {
        width: 100%;
        background-color: white;
        border-radius: 4px;
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }

    .text1 {
        font-size: 13px;
        font-weight: 500;
        color: #56575b
    }

    .text2 {
        font-size: 13px;
        font-weight: 500;
        margin-left: 6px;
        color: #56575b
    }

    .text3 {
        font-size: 13px;
        font-weight: 500;
        margin-right: 4px;
        color: #828386
    }

    .text3o {
        color: #00a5f4
    }

    .text4 {
        font-size: 13px;
        font-weight: 500;
        color: #828386
    }

    .text4i {
        color: #00a5f4
    }

    .text4o {
        color: white
    }

    .thumbup {
        font-size: 13px;
        font-weight: 500;
        margin-right: 5px
    }

    .thumbupo {
        color: #17a2b8
    }

    .sub-conatiner {
        width: 100%;
        height: 100%;
        margin: 36px auto;
        padding: 0;
    }

    .movie-content {
        width: 100%;
        margin-bottom: 10px;
    }

    .movie-content .title {
        height: 70px;
        margin: 15px 0;
    }

    .movie-content .title .title-kor {
        font-size: 40px;
    }

    .movie-content .title .title-eng {
        font-size: 20px;
        color: gray;
    }

    .movie-content .content {
        display: flex;
        height: 450px;
        overflow: hidden;
    }

    .movie-content .content .poster {
        display: inline-block;
        width: 320px;
        height: 450px;
        border-radius: 5px;
    }

    .movie-content .content .detail-content {
        margin-left: 20px;
        padding: 0;
        display: inline-block;
        width: calc(100% - 332px);
    }

    .line {
        height: 32px;
    }

    .movie-content .content .detail-content .div {
        margin-bottom: 30px;
    }

    .movie-content .content .detail-content .list-title {
        display: inline-block;
        width: 80px;
        margin-right: 20px;
        font-size: 146x;
        color: #56595C;
    }

    .list-title {
        color: #56595C;
        font-size: 16px;
        height: 36px;
    }

    .staffs-intro {
        display:flex;
        margin: 0;
    }

    .staff-content img {
        border-radius: 5px;
        margin: 0 20px 10px 0;
    }

    .staff-content p {
        margin: 0 20px 0 0;
        padding: 0;
        font-size: 14px;
    }

    .staff-content p:nth-child(2) {
        color: #56595C;
    }

</style>
{%endblock%}
{% block content %}
<div class="sub-container">
    <div class="movie-content">
        <div class="title">
            <span class="title-kor">{{movie.title_kor}}</span>
            <span class="title-eng">{{movie.title_eng}}</span>
        </div>
        <div class="content">
            <img class="poster" src="{{movie.poster_url}}" />
            <div class="detail-content">
                <div class="line rating_aud">
                    <span class="list-title">관람객 평점</span> <span>{{movie.rating_aud}} 점</span>
                </div>
                <div class="line rating-cri">
                    <span class="list-title">평론가 평점</span> <span>{{movie.rating_cri}} 점</span>
                </div>
                <div class="line rating_net div">
                    <span class="list-title">네티즌 평점</span> <span>{{movie.rating_net}} 점</span>
                </div>
                <div class="line genre">
                    <span class="list-title">장르</span> <span>{{movie.genre}}</span>
                </div>
                <div class="showtimes">
                    <span class="list-title">상영 시간</span> <span>{{movie.showtimes}}</span>
                </div>            
                <div class="line rate">
                    <span class="list-title">상영 등급</span> <span>{{movie.rate}}</span>
                </div>
                <div class="line release_date div">
                    <span class="list-title">개봉일</span> <span>{{movie.release_date}}</span>
                </div>
                <div class="line summary">
                    <span class="list-title">줄거리</span>
                    <p>{{movie.summary}}</p>
                </div>
        </div>
        </div>
    </div>
    <div class="line">
        <span class="list-title">인물 정보</span>
    </div>
    <div class="staffs-intro">
        {% for staff in staffs %}
        <div class="staff-content">
                <img src="{{staff.image_url}}" />
                <p>{{staff.role}}</p>
                <p>{{staff.name}}</p>
        </div>
        {% endfor %}
    </div>
    <div class="comment-content">

        <div></div>
        <div><span>한줄평</span></div>
        {% if user.is_authenticated %}
        <form action="{% url 'movie:comment_create' movie.id %}" method="POST">
            {% csrf_token %}
            <div class="comment-textarea">
                <input class="form-control" rows="1" name="content"></ㅑ>
                <button type="submit" class="btn btn-primary write-btn">작성</button>
            </div>


        </form>
        {% endif %}
        <div>
            {% for comment in comments%}

            <div class="d-flex justify-content-center py-2">
                <div class="second py-2 px-2  comment"> <span class="text1">{{comment.content}}</span>
                    <div class="d-flex justify-content-between py-1 pt-2">
                        <div><img src="https://i.imgur.com/tPvlEdq.jpg" width="18"><span
                                class="text2">{{comment.user}}</span></div>
                        <div><span class="text3">{{comment.created_at}}</span><span class="thumbup"><i
                                    class="fa fa-thumbs-o-up"></i></span><span class="text4"></span></div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
    {% endblock %}

movieproject/movie/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="row mb-2">
  <div
    class="col-lg-8"
    style="width: 30%; margin: 30px auto 15px auto; padding-bottom: 0"
  >
    <form class="form-inline" method="GET" action="">
      <div class="form-group mb-2">
        {% if query %}

        <input
          type="search"
          class="form-control searchQuery"
          id="movieTitle"
          name="query"
          value="{{query}}"
          placeholder="Ex) 인셉션"
        />
        {% else %}

        <input
          type="search"
          class="form-control searchQuery"
          id="movieTitle"
          name="query"
          placeholder="Ex) 인셉션"
        />
        {% endif %}
      </div>
    </form>
  </div>
</div>
<div
  class="index-container"
  style="
    margin-top: 0;
    width: 100%;
    height: 100%;
    padding: 0 160px 0 160px;
    display: flex;
    flex-wrap: wrap;
  "
>
  {% for movie in movies %}
  <div class="card" style="width: 25%; height: 50%; margin-bottom: 30px">
    <a
      href="{% url 'movie:detail' movie.id %}"
      style="text-decoration: none; height: 100%"
    >
      <img
        src="{{movie.poster_url}}"
        class="card-img-top"
        alt="..."
        style="object-fit: cover; height: 85%"
      />
      <div
        class="card-body"
        style="
          text-align: center;
          border-top: 1px solid rgba(0, 0, 0, 0.125);
          height: 15%;
          display: flex;
          justify-content: center;
          align-items: center;
        "
      >
        <p class="card-text" style="color: black">{{movie.title_kor}}</p>
      </div>
    </a>
  </div>
  {% endfor %}
  <div style="width: 100%; display: flex; justify-content: center">
    <nav aria-label="..." style="margin-top: 2%; margin-bottom: 2%">
      <ul class="pagination">
        {% if movies.has_previous %}
        <li class="page-item">
          <a href="?page=1&query={{ query }}" class="page-link">First</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a href="?page=1&query={{ query }}" class="page-link">First</a>
        </li>
        {% endif %} {% for page in page_range %} {% if page == movies.number %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">{{ page }}</span>
        </li>
        {% else %}
        <li class="page-item">
          <a href="?page={{page}}&query={{ query }}" class="page-link"
            >{{page}}</a
          >
        </li>
        {% endif %} {% endfor %} {% if movies.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ movies.paginator.num_pages }}"
            >Last</a
          >
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  {% endblock %}
</div>

movieproject/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Ruten Tomato</title>
    {% block css_content %} {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">루튼 토마토</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link disabled" aria-current="page" href="#"
                >{{user.username}}님 안녕하세요!</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'account:logout' %}"
                >로그아웃</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'account:login' %}"
                >로그인</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'account:signup' %}"
                >회원가입</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>